"""Regenerate the final figure set, and record what produced it.

Every figure in the paper comes from one command in `FINAL` below. Running this script
reproduces all of them and writes `figures/MANIFEST.json`, which pairs each output file with the
script and arguments that made it, the hash of the result set it read, and the git SHA and module
hashes of the code that was running.

Two failure modes this exists to prevent. A figure regenerated by hand with slightly different
arguments than last time, which is invisible in the PDF and fatal in a caption. And a figure left
in `figures/` from a superseded analysis, which is indistinguishable from a current one by
filename alone once the arm count happens to match — so anything not in `FINAL` is moved to
`figures/superseded/` rather than left where a reader might pick it up.

    python scripts/make_figures.py [--check]

`--check` regenerates nothing and only reports whether the manifest matches what is on disk,
which is the form to run before submitting.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src import provenance  # noqa: E402

# Imported for their side effect on the provenance registry, not for their names. The figure
# scripts run as subprocesses, so nothing they import registers in *this* process, and the
# manifest's `module_hashes` came out empty until these were added — a provenance field that was
# present, well-formed and carrying nothing.
from src.analysis import attribution, grid, timewarp  # noqa: E402,F401

FIGDIR = ROOT / "figures"

# figure id -> (script, args, what it is in the paper)
FINAL = {
    "fig2": ("scripts/fig2_gamma_sweep.py", ["--condition", "forgetting", "--lag", "12"],
             "Figure 2 — forgetting decomposes; channel mix shifts with richness (§5.1)"),
    "fig2_benign": ("scripts/fig2_gamma_sweep.py", ["--condition", "S-HH", "--lag", "12"],
                    "Figure S — the benign corner gains retained capacity (§5.1)"),
    "fig2_lag4": ("scripts/fig2_gamma_sweep.py",
                  ["--condition", "forgetting", "--lag", "4", "--task", "0"],
                  "Figure S — composition holds at a shorter lag (§5.3)"),
    "fig4": ("scripts/fig4_corners_rho_c.py", ["--gamma", "10"],
             "Figure 4 — center correlation across the 2×2 (§5.4)"),
    "fig4_gamma3": ("scripts/fig4_corners_rho_c.py", ["--gamma", "3"],
                    "Figure S — the same at γ₀ = 3, where S-HL has not yet appeared (§5.4)"),
    "fig_width": ("scripts/fig_width_invariance.py", ["--lag", "12"],
                  "Figure S — width robustness in Figure 2's form (§5.3)"),
}


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def run(fig_id: str, script: str, args: list[str]) -> list[Path]:
    """Run one figure script and return the files it wrote, by mtime snapshot."""
    before = {p: p.stat().st_mtime_ns for p in FIGDIR.glob("*") if p.is_file()}
    out = subprocess.run([sys.executable, str(ROOT / script), *args],
                         capture_output=True, text=True, cwd=ROOT)
    if out.returncode != 0:
        sys.exit(f"{fig_id}: {script} failed\n{out.stdout}\n{out.stderr}")
    return sorted(p for p in FIGDIR.glob("*")
                  if p.is_file() and before.get(p) != p.stat().st_mtime_ns)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the manifest against disk without regenerating")
    ap.add_argument("--submission", action="store_true",
                    help="with --check, also require that every figure is traceable to a "
                         "committed script and a named result set")
    args = ap.parse_args()
    manifest_path = FIGDIR / "MANIFEST.json"

    if args.check:
        if not manifest_path.exists():
            sys.exit("no manifest — run without --check first")
        man = json.loads(manifest_path.read_text())
        bad = []
        for fig_id, entry in man["figures"].items():
            for name, digest in entry["outputs"].items():
                p = FIGDIR / name
                if not p.exists():
                    bad.append(f"{fig_id}: {name} is missing")
                elif sha256_file(p) != digest:
                    bad.append(f"{fig_id}: {name} differs from the manifest")
        stale = sorted({p.name for p in FIGDIR.glob("*")
                        if p.is_file() and p.name != "MANIFEST.json"}
                       - {n for e in man["figures"].values() for n in e["outputs"]})
        for s in stale:
            bad.append(f"not in the manifest: {s}")
        # Matching disk is not the same as being reproducible. A figure whose inputs are unnamed,
        # or which was drawn from an uncommitted working tree, is byte-identical to one that is
        # neither of those things, so the distinction has to be asked for separately.
        if args.submission:
            for fig_id, entry in sorted(man["figures"].items()):
                if not entry.get("result_set_sha"):
                    bad.append(f"{fig_id}: no result_set_sha — inputs are unnamed")
                if not entry.get("n_arms"):
                    bad.append(f"{fig_id}: no n_arms recorded")
            if man.get("git_dirty"):
                bad.append(f"generated from a dirty tree at {man['git_sha']} — the scripts that "
                           f"drew these figures are not the scripts at that commit")
            if not man.get("module_hashes"):
                bad.append("module_hashes is empty — no code fingerprint recorded")
        print("\n".join(bad) if bad else "manifest matches disk")
        sys.exit(1 if bad else 0)

    # Anything already present that the final set does not claim is superseded by definition.
    keep: set[str] = set()
    figures = {}
    for fig_id, (script, argv, caption) in FINAL.items():
        produced = run(fig_id, script, argv)
        if not produced:
            sys.exit(f"{fig_id}: {script} wrote nothing")
        keep |= {p.name for p in produced}
        meta = next((json.loads(p.read_text()) for p in produced if p.suffix == ".json"), {})
        figures[fig_id] = {
            "caption": caption,
            "script": script,
            "args": argv,
            "command": f"python {script} {' '.join(argv)}".strip(),
            "result_set_sha": meta.get("result_set_sha"),
            "n_arms": meta.get("n_arms"),
            "outputs": {p.name: sha256_file(p) for p in produced},
        }
        print(f"  {fig_id:<12} {figures[fig_id]['command']}")

    trash = FIGDIR / "superseded"
    moved = []
    for p in sorted(FIGDIR.glob("*")):
        if p.is_file() and p.name not in keep and p.name != "MANIFEST.json":
            trash.mkdir(exist_ok=True)
            shutil.move(str(p), str(trash / p.name))
            moved.append(p.name)

    manifest_path.write_text(json.dumps({
        "generated_by": "scripts/make_figures.py",
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git_sha": provenance.git_sha(),
        "git_dirty": provenance.git_dirty(),
        "module_hashes": provenance.code_stamp()["modules"],
        "figures": figures,
        "moved_to_superseded": moved,
    }, indent=2) + "\n")
    print(f"\nwrote {manifest_path.relative_to(ROOT)}"
          f"{f'; moved {len(moved)} superseded file(s)' if moved else ''}")


if __name__ == "__main__":
    main()
